# Generated by Django 3.2.8 on 2021-11-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_quote_tag2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdepartment',
            old_name='name',
            new_name='subDep',
        ),
    ]
